### ISSUE TITLE
summarizeSccsAnalyses - blank sccsEraDataFolder entries

### ISSUE THREAD

**Issue by alondhe** [OHDSI/SelfControlledCaseSeries#11]
Hi @schuemie ,

I'm pretty new to the SCCS package, but I noticed that when trying to invoke summarizeSccsAnalyses, it runs into an error because the outcomeModelReference's sccsEraDataFolder array contains blank entries and it thus cannot run loadSccsEraData to load data from a blank location. 

First off, should these blank entries exist? 

I did make a fork and add a 'quick and dirty' check for the sccsEraDataFolder being blank in the for loop:
https://github.com/alondhe/SelfControlledCaseSeries/commit/293e2758d2a1ed39d1829a0503532e70e195a228#diff-335db7e884e649ff936f1cd1728fc9ad 

This allowed the function to ignore the blanks and process the summary.

Thanks,
Ajit

**Comment by schuemie** [comment]
Hi @alondhe,

Nope, those entries should not be empty. Could you mail me your analysis code so I reproduce the problem?

**Comment by alondhe** [comment]
Forgot to close this earlier -- I had a bug in my code :)
