### ISSUE TITLE
Problems loading up packages

### ISSUE THREAD

**Issue by oxonnsn** [OHDSI/SelfControlledCaseSeries#12]
**Hi there, I'm new to R and the SCCS package - but have been having problems loading up the SCCS package. I'm running MacOS High Sierra and I've installed Java - checked on Terminal -**  
adminsmac$ java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

**- but when loading the SCCS package:**
"install.packages("devtools")
library(devtools)
install_github("ohdsi/OhdsiRTools")
install_github("ohdsi/SqlRender")
install_github("ohdsi/DatabaseConnector")
install_github("ohdsi/Cyclops")
install_github("ohdsi/SelfControlledCaseSeries")" 

**- I am getting the error messages:**
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so
  Reason: image not found
ERROR: lazy loading failed for package ‘SqlRender’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/SqlRender’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/SqlRender’
Installation failed: Command failed (1)

**Do you have any advice?
Many thanks!**

**Total script:**
> install.packages("devtools")
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/devtools_1.13.4.tgz'
Content type 'application/x-gzip' length 439078 bytes (428 KB)
==================================================
downloaded 428 KB

The downloaded binary packages are in
	/var/folders/w9/03_q4w_s2wg9sl82dl2j7yy40000gp/T//RtmpeTtEZr/downloaded_packages
> library(devtools)
> install_github("ohdsi/OhdsiRTools")
Skipping install of 'OhdsiRTools' from a github remote, the SHA1 (38585047) has not changed since last install.
  Use `force = TRUE` to force installation
Warning message:
In strptime(x, fmt, tz = "GMT") :
  unknown timezone 'zone/tz/2017c.1.0/zoneinfo/Europe/London'
> install_github("ohdsi/SqlRender")
Downloading GitHub repo ohdsi/SqlRender@master
from URL https://api.github.com/repos/ohdsi/SqlRender/zipball/master
Installing SqlRender
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/w9/03_q4w_s2wg9sl82dl2j7yy40000gp/T/RtmpeTtEZr/devtools11ce44132b91d/OHDSI-SqlRender-558bbe0'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘SqlRender’ ...
Warning in as.POSIXlt.POSIXct(x, tz) :
  unknown timezone 'zone/tz/2017c.1.0/zoneinfo/Europe/London'
** R
** inst
** tests
** preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so
  Reason: image not found
ERROR: lazy loading failed for package ‘SqlRender’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/SqlRender’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/SqlRender’
Installation failed: Command failed (1)
> install_github("ohdsi/DatabaseConnector")
Downloading GitHub repo ohdsi/DatabaseConnector@master
from URL https://api.github.com/repos/ohdsi/DatabaseConnector/zipball/master
Installing DatabaseConnector
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/w9/03_q4w_s2wg9sl82dl2j7yy40000gp/T/RtmpeTtEZr/devtools11ce43d5cfefa/OHDSI-DatabaseConnector-2ae287e'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘DatabaseConnector’ ...
Warning in as.POSIXlt.POSIXct(x, tz) :
  unknown timezone 'zone/tz/2017c.1.0/zoneinfo/Europe/London'
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘DatabaseConnector’:
 .onLoad failed in loadNamespace() for 'DatabaseConnector', details:
  call: NULL
  error: .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so
  Reason: image not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/DatabaseConnector’
Installation failed: Command failed (1)
> install_github("ohdsi/Cyclops")
Skipping install of 'Cyclops' from a github remote, the SHA1 (08e76d63) has not changed since last install.
  Use `force = TRUE` to force installation
> install_github("ohdsi/SelfControlledCaseSeries")
Downloading GitHub repo ohdsi/SelfControlledCaseSeries@master
from URL https://api.github.com/repos/ohdsi/SelfControlledCaseSeries/zipball/master
Installing SelfControlledCaseSeries
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/w9/03_q4w_s2wg9sl82dl2j7yy40000gp/T/RtmpeTtEZr/devtools11ce4741c7be2/OHDSI-SelfControlledCaseSeries-e4519c9'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

ERROR: dependency ‘DatabaseConnector’ is not available for package ‘SelfControlledCaseSeries’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/SelfControlledCaseSeries’
Installation failed: Command failed (1)
> library(SelfControlledCaseSeries)
Error in library(SelfControlledCaseSeries) : 
  there is no package called ‘SelfControlledCaseSeries’

**Comment by schuemie** [comment]
@PRijnbeek sent me this solution some time ago:

```
sudo ln -s $(/usr/libexec/java_home)/jre/lib/server/libjvm.dylib /usr/local/lib
sudo R CMD javareconf
install.packages("rJava",type='source')
```

Peter, maybe you can elaborate?
