### ISSUE TITLE
fakeDf performance and refactoring

### ISSUE THREAD

**Issue by msuchard** [OHDSI/SelfControlledCaseSeries#2]
1. Should we consider moving `fakeDf` into a separate package for reuse in other OHDSI methods?

2. Would for-loops in `fakeDf` be more performant rewritten as `apply`?  For example:

```{r}
  fakeDf <- vector(length = length(ffdf), mode = "list")
  for (i in 1:length(ffdf)){
    fakeDf[[i]] <- ffdf[index,i]
  }
```

as

```{r}
fakeDf <- lapply(ffdf, function(x) { x[index] })
```

**Comment by schuemie** [comment]
1. Yes, we could do that. There are other things that most method packages will need, such as methods used in running the all-by-all-by-all. (subsetting and filtering of lists of parameters). I was thinking of adding them to OhdsiRTools, but we could also create a new package with all things required at run-time (OhdsiRTools currently only contains tools for design-time). What do you think?

2. Sure, I'll do that. It's just looping over the columns (n is usually around 4 or 5), so not expecting massive performance boosts.

**Comment by msuchard** [comment]
I vote for inclusion in `OhdsiRTools` until that package gets too bloated.

**Comment by schuemie** [comment]
I moved the functions to OhdsiRTools. I was not able to use lapply on ffdf objects so I stuck with the for loops.
