### ISSUE TITLE
simulatesccsdata function in SCCS packages

### ISSUE THREAD

**Issue by hlblb** [OHDSI/SelfControlledCaseSeries#24]
Hello~.
I try to use the SCCS package
standardsccs function and semisccs function in the package seem working. 
However when I try to run the code in the documents

set.seed(4321)
arisk <- round(runif(110,366,730)) # ages at start of exposure
simdata <- simulatesccsdata(nindivs=110, astart=366, aend=730,
                            adrug=arisk, aedrug=arisk+20, eexpo=2.5)
                            
simdata

It only return "[1] 1 0", not the generated data. Computers in my university lab and my friend's computer return the same thing.
I did not change any code; I just copy the code to see what happen.

Do you know what the problem is and how to solve it?
I am using windows 10.

Thank you~

**Comment by schuemie** [comment]
I think your issue refers to the [SCCS package](https://cran.r-project.org/web/packages/SCCS/index.html), which is a different package. (The SelfControlledCaseSeries package is aimed at working directly against the OMOP Common Data Model). I'm sorry for the confusion the similarity in names causes. 

For your question I would contact the maintainer of the SCCS package as listed in CRAN.
