### ISSUE TITLE
Error with createStudyPopulation function

### ISSUE THREAD

**Issue by Xintong-Li-ZnCu** [OHDSI/SelfControlledCaseSeries#25]
I was following the instructions in the vignette 'Single studies using the SelfControlledCaseSeries package' and received the following error message
``
> studyPop <- createStudyPopulation(sccsData = sccsData,
                                   outcomeId = 1,
                                   firstOutcomeOnly = FALSE,
                                   naivePeriod = 180)
Error: Problem with `mutate()` input `startAgeInDays`.
x must be a double vector, not an integer vector.
ℹ Input `startAgeInDays` is `case_when(...)`.
```

**Comment by schuemie** [comment]
Could you tell me what database platform you're using? Oracle?

**Comment by Xintong-Li-ZnCu** [comment]
I'm using PostgreSQL

**Comment by schuemie** [comment]
Could you try using the latest develop version of DatabaseConnector?:
```
remotes::install_github("ohdsi/DatabaseConnector", ref = "develop")
```

You will need to redo the data extraction (`getDbSccsData`) after installing the updated DatabaseConnector.

**Comment by Xintong-Li-ZnCu** [comment]
Thank you! it worked!

**Comment by schuemie** [comment]
(Note that this version of DatabaseConnector has since been released, so there's no more need to use the develop branch)
