### ISSUE TITLE
sccs_spline.knot_month integer value

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/SelfControlledCaseSeries#39]
Based on [ref](https://github.com/OHDSI/SelfControlledCaseSeries/blob/develop/inst/csv/resultsDataModelSpecification.csv#L31), `sccs_spline.knot_month` is set to an integer value but in some testing, I've found this to be a float value. I wanted to confirm that this should be a float in `resultsDataModelSpecification.csv` and not a bug in the expected value of `knot_month`?

**Comment by schuemie** [comment]
Nope, `knot_month` should definitely be an integer. What values are you observing?

**Comment by schuemie** [comment]
Sorry, scratch that. The spline knot can definitely be a float. I'll fix the results model
