### ISSUE TITLE
sccs_spline export contains duplicated rows

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/SelfControlledCaseSeries#56]
Under certain circumstances (which are unclear to me) the sccs_spline.csv contains duplicated rows that violate the primary key for the sccs_spline table. Performing a `unique()` on the sccs_spline data fixes the issue when uploading.

**Comment by schuemie** [comment]
Fixed in https://github.com/OHDSI/SelfControlledCaseSeries/commit/8ad50eb17668bc8bd0f837d87f0b0ff0f9ea4f59
